security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\Customer: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Customer
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            stateless: false
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: email
                password_parameter: password
            logout:
                path: app_logout
                target: app_login

    access_control: []
